### ISSUE TITLE
The number of entities in the provided knowledge_embedding does not match with Wikidata5m

### ISSUE THREAD

**Issue by hour01** [thunlp/Knowledge-Plugin#2]
Hi, thanks for the excellent work and paper. 
The paper mentions that you used the Wikidata5m as the knowledge graph and excluded some triples in downstream tasks.
After downloading the knowledge_embedding from `https://thunlp.oss-cn-qingdao.aliyuncs.com/zzy/knowledge_embedding.tar` and loading it by `KE_Embedding` in `all_embedding.py`, I observed that there are 5,040,986 entities in total, which doesn't match the number of entities in [Wikidata5m (4,594,485)](https://deepgraphlearning.github.io/project/wikidata5m).
I am confused about this. Did I miss or misunderstand something?

**Comment by zzy14** [comment]
Thank you for your interest in our work and for highlighting the discrepancy in entity counts. You are correct; there is a mismatch. We used entity descriptions from Wikidata5m for RA and entity embeddings from [ERNIE](https://github.com/thunlp/ERNIE) for E-BERT and Map-tuning. Both of these sources contain approximately 5 million entities, leading to the mismatch you've noticed. We will update the paper on arXiv to correct this error. Thank you once again for pointing out this inconsistency.

**Comment by hour01** [comment]
Thanks for your explanation.
