### ISSUE TITLE
缺少./datasets/FewRel/test_wiki.json文件

### ISSUE THREAD

**Issue by LiyiLily** [thunlp/Knowledge-Plugin#3]
按照readme文件下载相关数据集后，发现缺少./datasets/FewRel/test_wiki.json文件，无法进行FewRel数据集的相关实验，请问该如何获取该文件。另外在已下载的文件中发现./datasets/FewRel/submission/test_wiki_input-N-K.json文件，代码中并未使用该数据文件，请问是否和test_wiki.json文件相关，该如何使用呢？

**Comment by Zhiyuan-Zeng** [comment]
@LiyiLily 你好，感谢你对我们工作的兴趣！关于你提出的问题，请参考[这个issue](https://github.com/thunlp/Knowledge-Plugin/issues/1)。谢谢！

**Comment by LiyiLily** [comment]
> @LiyiLily 你好，感谢你对我们工作的兴趣！关于你提出的问题，请参考[这个issue](https://github.com/thunlp/Knowledge-Plugin/issues/1)。谢谢！

明白了，感谢回复！

**Comment by skywalker-yst** [comment]
> > [@LiyiLily](https://github.com/LiyiLily) 你好，感谢你对我们工作的兴趣！关于你提出的问题，请参考[这个issue](https://github.com/thunlp/Knowledge-Plugin/issues/1)。谢谢！
> 
> 明白了，感谢回复！

请问你是如何解决这个问题，从而实现FewRel项目的呢，我也和你一样的问题

**Comment by skywalker-yst** [comment]
> > > [@LiyiLily](https://github.com/LiyiLily) 你好，感谢你对我们工作的兴趣！关于你提出的问题，请参考[这个issue](https://github.com/thunlp/Knowledge-Plugin/issues/1)。谢谢！
> > 
> > 
> > 明白了，感谢回复！
> 
> 请问你是如何解决这个问题，从而实现FewRel项目的呢，我也和你一样的问题

@LiyiLily

**Comment by Zhiyuan-Zeng** [comment]
@skywalker-yst I would recommend submitting your results to the official leaderboard of FewRel. More details are [here](https://github.com/thunlp/Knowledge-Plugin#fewrel-submission). Thanks!
