### ISSUE TITLE
FewRel数据集实验结果复现问题

### ISSUE THREAD

**Issue by LiyiLily** [thunlp/Knowledge-Plugin#4]
您好！
实验过程中发现使用提供的FewRel数据集的checkpoints提交测试，结果只有20%~25%（测试了BaseModel BERT 和 Plug_TaskSpecific）。
而后我使用提供的代码在FewRel数据集上跑 BaseModel BERT 实验，提交测试，结果约89%，与论文中汇报的baseline结果有一定差距。
由于BaseModel BERT 模型是其它对比试验的基准，目前也无法复现Knowledge-Plugin在该数据集上的结果。
请问是否可以提供FewRel数据集可用的BaseModel的checkpoints文件？

**Comment by Zhiyuan-Zeng** [comment]
@LiyiLily 你好，感谢你对我们工作的兴趣！请问你使用的是哪里提供的checkpoints？请参考[正确的checkpoints下载方式](https://github.com/thunlp/Knowledge-Plugin?tab=readme-ov-file#checkpoints)。

在下载了checkpoints之后，可以参考[这里的指南](https://github.com/thunlp/Knowledge-Plugin?tab=readme-ov-file#fewrel-submission)运行命令：`python FewRel_submission.py --config config/FewRel/BaseModel/BERT_5way1shot.config --checkpoint ../output/FewRel/BaseModel/BERT_5way1shot/ckpt.bin --data_path ../datasets/FewRel/submission --data_name test_wiki_input`。

最后**请将得到的四个结果文件打包为一个压缩包**提交到[官方提交窗口](https://codalab.lisn.upsaclay.fr/competitions/7395)。这里附上正确的[pred-5-1.json](https://github.com/thunlp/Knowledge-Plugin/files/14819448/pred-5-1.json)以供参考，根据官方的测试结果其准确率为90.95%。

**Comment by LiyiLily** [comment]
非常感谢您的回复，我大概是之前下载错了checkpoints，重新尝试后已经解决

**Comment by Zhiyuan-Zeng** [comment]
@LiyiLily Thanks! We updated [all results](https://github.com/thunlp/Knowledge-Plugin/commit/3b042d43f2cddefaa50ce08cd5feb89a41e7dba4) for that.
